### ISSUE TITLE
Support macOS with Metal

### ISSUE THREAD

**Issue by aleksigron** [aleksigron/kokko#47]
In order to support the modern graphics features Kokko might want to use on macOS, we need to implement support for the Metal rendering API. When running on Metal, Xcode also provides very good graphics debugging tools that are better than anything found on OpenGL or Vulkan, which could make debugging and profiling much easier. Metal fits somewhere between OpenGL and Vulkan when it comes to abstraction level, so supporting Metal makes it slightly easier to implement support for Vulkan in the future.

- [x] Basic support: project builds and renders a background color to the screen
- [ ] Basic shader & vertex buffers: a fixed shader can be compiled and rendered using a fixed vertex buffer
- [ ] Mesh support: glTF meshes can be loaded from assets and rendered with a fixed shader
- [ ] Shader support: shaders can be loaded, cross-compiled from GLSL and rendered
- [ ] Texture support: textures can be loaded and used in shaders
- [ ] ImGUI support: editor UI works
- [ ] Environment map can be loaded and rendered to scene view
- [ ] Render scene entities to scene view
- [ ] Post-process effects: SSAO and Bloom

**Comment by SamoZ256** [comment]
Do you still work on Metal support? Because it does not build anymore

**Comment by aleksigron** [comment]
Thanks for the report @SamoZ256. I will try to fix the macOS build soon. Do bear in mind that this feature is in very early stages, and I can't promise any timelines for the implementation.

**Comment by aleksigron** [comment]
@SamoZ256 MacOS build is fixed with PR #59. Now the project is also built for macOS and unit tests are run on CI, so it shouldn't break again.
