### ISSUE TITLE
Improve model handling

### ISSUE THREAD

**Issue by aleksigron** [aleksigron/kokko#64]
- [x] Implement loading glTF models with node hierarchy, multiple meshes and mesh primitives (#63)
- [x] Implement model removal and storage reuse (#66)
- [x] Rename mesh primitive to mesh part (#65)
- [x] Support selecting a specific mesh from a model with multiple meshes to be used in a mesh component (#67)
- [x] Support setting a material for each mesh part (#68)
- [x] Support rendering mesh parts with different transparency types from the same mesh (#68)
- [x] Support creating a hierarchy of nodes in the scene from a model (#69)
